apiVersion: v1
kind: Service
metadata:
  name: hello-world-svc
spec:
  selector:
    tier: frontend
    version: v1
  ports:
    - port: 5858
      targetPort: 5858
      protocol: TCP
  type: NodePort
